# Version Details: v0.4
# Modular, DRY, and recursive shell loader setup with .scriptignore support
add2bash() {
  local bashrc="$HOME/.bashrc"
  local cwd="$PWD"
  local loader_file="$cwd/load_all.sh"
  local text=""
  local marker="# [add2bash] Central Loader for $cwd"

  # [DRY] Função interna para centralizar a confirmação do usuário
  confirm_action() {
    local prompt_msg="$1"
    local reply
    read -rp "$prompt_msg [y/N] " reply
    case "$reply" in
      [yY]|[yY][eE][sS]) return 0 ;;
      *) return 1 ;;
    esac
  }

  # [DRY] Função interna para checar idempotência (evitar duplicados)
  is_already_added() {
    local search_text="$1"
    local target_file="$2"
    grep -Fq "$search_text" "$target_file" 2>/dev/null
  }

  # CASO 1: Usuário passou um argumento (texto personalizado)
  if [[ -n "$1" ]]; then
    text="$1"

    if is_already_added "$text" "$bashrc"; then
      echo "Info: This exact text already exists in $bashrc. Skipping."
      return 0
    fi

    cat <<EOF
The following custom text will be appended to:
  $bashrc

$text
EOF

    if confirm_action "Proceed?"; then
      printf '\n%s\n' "$text" >> "$bashrc"
      echo "Appended to $bashrc"
    else
      echo "Cancelled."
    fi
    return 0
  fi

  # CASO 2: Sem argumentos (Rota da Opção B - Recursivo com Loader Central + Ignore)
  
  # 2.1. Criação/Atualização do Loader Central (load_all.sh)
  # Nota: Removemos o 'if' que impedia a recriação para garantir que, se atualizarmos a lógica do loader, ele reescreva o arquivo com a versão nova.
  echo "Generating/Updating central loader script at: $loader_file"
  cat << 'EOF' > "$loader_file"
#!/usr/bin/env bash
# Central loader generated by add2bash
# Scans directories recursively for .sh files, respects .scriptignore, and sources them safely.

CURRENT_DIR="$(dirname "$(readlink -f "$BASH_SOURCE")")"
IGNORE_FILE="$CURRENT_DIR/.scriptignore"

# Cria um array com os padrões a serem ignorados
IGNORE_PATTERNS=()
if [[ -f "$IGNORE_FILE" && -r "$IGNORE_FILE" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    # Remove espaços em branco nas pontas
    line=$(echo "$line" | xargs 2>/dev/null)
    # Ignora linhas vazias e comentários
    if [[ -n "$line" && ! "$line" =~ ^# ]]; then
      IGNORE_PATTERNS+=("$line")
    fi
  done < "$IGNORE_FILE"  # <-- A CORREÇÃO ESTÁ AQUI (era 'fi < ...', o certo é 'done < ...')
fi

# Busca todos os arquivos .sh recursivamente
while IFS= read -r -d '' f; do
  # 1. Validações básicas de segurança
  if [[ "$f" == "$BASH_SOURCE" || ! -f "$f" || ! -r "$f" ]]; then
    continue
  fi

  # 2. Verifica se o arquivo ou caminho bate com algum padrão do .scriptignore
  skip=false
  for pattern in "${IGNORE_PATTERNS[@]}"; do
    if [[ "$f" == *"$pattern"* ]]; then
      skip=true
      break
    fi
  done

  # 3. Se não estiver na lista de ignore, carrega o script
  if [[ "$skip" == false ]]; then
    source "$f"
  fi
done < <(find "$CURRENT_DIR" -type f -name "*.sh" -print0)
EOF
  chmod +x "$loader_file"

  # 2.2. Preparação do texto que vai para o .bashrc
  text=$(cat <<EOF
$marker
if [ -f "$loader_file" ]; then
    source "$loader_file"
fi
EOF
)

  # Checa idempotência antes de tocar no .bashrc
  if is_already_added "$marker" "$bashrc"; then
    echo "Info: This directory loader is already configured in $bashrc. Nothing to do."
    return 0
  fi

  cat <<EOF
No custom text provided. Setting up recursive directory loader.
The following lines will be appended to:
  $bashrc

$text
EOF

  if confirm_action "Proceed with .bashrc modification?"; then
    {
      echo ""
      printf '%s\n' "$text"
    } >> "$bashrc"
    echo "Success! Lines added to $bashrc"
    echo "Now, any .sh file inside '$cwd' (or its subfolders) will be loaded automatically."
  else
    echo "Cancelled .bashrc modification."
  fi
}

# DETECÇÃO INTELIGENTE: Executar se chamado direto, ou apenas carregar se via source
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    add2bash "$@"
fi