# Version Details: v0.5
# Definitive recursive shell loader setup with advanced .scriptignore pattern matching
add2bash() {
  local bashrc="$HOME/.bashrc"
  local cwd="$PWD"
  local loader_file="$cwd/load_all.sh"
  local text=""
  local marker="# [add2bash] Central Loader for $cwd"

  # [DRY] Função interna para centralizar a confirmação do usuário
  confirm_action() {
    local prompt_msg="$1"
    local reply
    read -rp "$prompt_msg [y/N] " reply
    case "$reply" in
      [yY]|[yY][eE][sS]) return 0 ;;
      *) return 1 ;;
    esac
  }

  # [DRY] Função interna para checar idempotência (evitar duplicados)
  is_already_added() {
    local search_text="$1"
    local target_file="$2"
    grep -Fq "$search_text" "$target_file" 2>/dev/null
  }

  # CASO 1: Usuário passou um argumento (texto personalizado)
  if [[ -n "$1" ]]; then
    text="$1"

    if is_already_added "$text" "$bashrc"; then
      echo "Info: This exact text already exists in $bashrc. Skipping."
      return 0
    fi

    cat <<EOF
The following custom text will be appended to:
  $bashrc

$text
EOF

    if confirm_action "Proceed?"; then
      printf '\n%s\n' "$text" >> "$bashrc"
      echo "Appended to $bashrc"
    else
      echo "Cancelled."
    fi
    return 0
  fi

  # CASO 2: Sem argumentos (Rota da Opção B - Loader Central com Ignore Avançado)
  echo "Generating/Updating central loader script at: $loader_file"
  cat << 'EOF' > "$loader_file"
#!/usr/bin/env bash
# Central loader generated by add2bash
# Scans directories recursively for .sh files, respects advanced .scriptignore rules, and sources them safely.

CURRENT_DIR="$(dirname "$(readlink -f "$BASH_SOURCE")")"
IGNORE_FILE="$CURRENT_DIR/.scriptignore"

# Cria um array com os padrões a serem ignorados
IGNORE_PATTERNS=()
if [[ -f "$IGNORE_FILE" && -r "$IGNORE_FILE" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    # Remove retorno de carro (\r) e espaços extras nas pontas
    line=$(echo "$line" | tr -d '\r' | xargs 2>/dev/null)
    
    # Ignora linhas vazias e comentários
    if [[ -n "$line" && ! "$line" =~ ^# ]]; then
      IGNORE_PATTERNS+=("$line")
    fi
  done < "$IGNORE_FILE"
fi

# Busca todos os arquivos .sh recursivamente
while IFS= read -r -d '' f; do
  # 1. Validações básicas de segurança
  if [[ "$f" == "$BASH_SOURCE" || ! -f "$f" || ! -r "$f" ]]; then
    continue
  fi

  # Caminho relativo a partir da raiz da pasta de scripts (ex: ArchivePar2/script.sh)
  RELATIVE_PATH="${f#$CURRENT_DIR/}"

  # 2. Verifica as regras do .scriptignore
  skip=false
  for pattern in "${IGNORE_PATTERNS[@]}"; do
    
    # Se o padrão começar com '/', o match deve ser exato a partir da raiz da pasta de scripts
    if [[ "$pattern" == /* ]]; then
      # Remove a barra inicial do padrão para comparar com o RELATIVE_PATH
      clean_pattern="${pattern#/}"
      
      # Verifica se o caminho relativo começa exatamente com o padrão ou se é a própria pasta
      if [[ "$RELATIVE_PATH" == "$clean_pattern"* ]]; then
        skip=true
        break
      fi
    else
      # Se NÃO começar com '/', faz o "match global" (em qualquer parte do caminho ou nome do arquivo)
      if [[ "$RELATIVE_PATH" == *"$pattern"* ]]; then
        skip=true
        break
      fi
    fi
  done

  # 3. Se não foi ignorado, executa o source
  if [[ "$skip" == false ]]; then
    source "$f"
  fi
done < <(find "$CURRENT_DIR" -type f -name "*.sh" -print0)
EOF
  chmod +x "$loader_file"

  # 2.2. Preparação do texto que vai para o .bashrc
  text=$(cat <<EOF
$marker
if [ -f "$loader_file" ]; then
    source "$loader_file"
fi
EOF
)

  if is_already_added "$marker" "$bashrc"; then
    echo "Info: This directory loader is already configured in $bashrc. Nothing to do."
    return 0
  fi

  cat <<EOF
No custom text provided. Setting up recursive directory loader.
The following lines will be appended to:
  $bashrc

$text
EOF

  if confirm_action "Proceed with .bashrc modification?"; then
    {
      echo ""
      printf '%s\n' "$text"
    } >> "$bashrc"
    echo "Success! Lines added to $bashrc"
  else
    echo "Cancelled .bashrc modification."
  fi
}

# DETECÇÃO INTELIGENTE
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    add2bash "$@"
fi